# Generated by Django 5.1.6 on 2025-02-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscaping_api', '0007_alter_service_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='service_images/'),
        ),
    ]
