# Generated by Django 5.1.6 on 2025-02-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscaping_api', '0008_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='landscaping_api.image'),
        ),
    ]
