# Generated by Django 5.1.6 on 2025-02-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscaping_api', '0009_alter_service_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='beforeAfter_images/')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=400)),
            ],
        ),
    ]
