# Generated by Django 5.1.6 on 2025-02-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscaping_api', '0005_contact_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detailed_description',
            field=models.TextField(null=True),
        ),
    ]
