# Generated by Django 5.1.6 on 2025-02-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscaping_api', '0006_service_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='images',
            field=models.ManyToManyField(null=True, to='landscaping_api.image'),
        ),
    ]
